# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: alpine

pipelines:
  branches:
    # Master branch deployment to live - no drafts
    master:
      - step:
          deployment: production   # set to test, staging or production
          name: Build Hugo Web Site.
          script:
            - apk add --no-cache python3
            - apk add --no-cache hugo
            - apk add --no-cache tree
            - apk add --no-cache git
            - python3 -m ensurepip
            - pip3 install --upgrade pip setuptools
            - pip3 install awscli

            - cd /opt/atlassian/pipelines/agent/build
            - git submodule update --init --recursive
            - hugo
            - tree ./public

            - aws s3 sync --delete --web ./public $S3_BUCKET
