# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: alpine

pipelines:
  branches:
    # Master branch deployment to live - no drafts
    master:
      - step:
          name: Install Base Tools
          script:
            - apk add --no-cache python3
            - apk add --no-cache hugo
            - apk add --no-cache tree
            - apk add --no-cache git
            - python3 -m ensurepip
            - pip3 install --upgrade pip setuptools
            - pip3 install awscli

      - step:
          name: HUGO Build
          deployment: production   # set to test, staging or production
          script:
            - cd /opt/atlassian/pipelines/agent/build
            - /usr/local/git submodule update --init --recursive
            - /usr/local/hugo
            - /usr/local/tree ./public

      - step:
          name: Deploy to S3
          image: atlassian/pipelines-awscli
          script:
            - /usr/local/aws s3 sync --delete ./public $S3_BUCKET
